### PR TITLE
Convert to a 'Go Module'

### PR DESCRIPTION
**Pull request by kataras**
Conver to a [Go Module](https://blog.golang.org/using-go-modules).

/CC @tmlayton

### CODE REVIEW

**Comment by kataras** [comment]
image

**Comment by tmlayton** [comment]
Hey @kataras—it’s not a bug, more of a missing feature. The CLA check does not automatically rerun after signing and needs to be rerun manually.

**Comment by kataras** [comment]
> Hey @kataras—it’s not a bug, more of a missing feature. The CLA check does not automatically rerun after signing and needs to be rerun manually.

I see, that's OK! Why isn't that merged though? We use that on [Iris](https://github.com/kataras/iris) and I am trying to convert every single dependency of it to a go-module, so far with success.

**Comment by mkobetic** [comment]
The change itself looks OK to me, but I'm trying to find someone from our projects that still rely on this repo to judge the impact.

**Comment by JamesOwenHall** [comment]
cc @Shopify/data-distribution

**Comment by erinwild** [comment]
Closing; we've merged https://github.com/Shopify/goreferrer/pull/42 now.

**Pull request closed without merging**
